# Generated by Django 5.2.6 on 2025-09-24 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("electronics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="networknode",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_for_nodes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Контактное лицо",
            ),
        ),
        migrations.AddField(
            model_name="networknode",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="network_nodes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудники",
            ),
        ),
        migrations.AddField(
            model_name="networknode",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="electronics.networknode",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="network_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="electronics.networknode",
                verbose_name="Звено сети",
            ),
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(fields=["city"], name="electronics_city_1f2ab7_idx"),
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(
                fields=["supplier"], name="electronics_supplie_67f70a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(
                fields=["node_type"], name="electronics_node_ty_c3cdd0_idx"
            ),
        ),
    ]
